sudo: required
services: 
  - docker

before_install:
  - docker build -t docker-react-testimage -f Dockerfile.dev .

scripts:
  - docker run docker-react-testimage npm run test -- --coverage
  # - docker run -e CI=true USERNAME/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "dockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-387657282676"
  bucket_path: "docker-react"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
