version : "3"
services :
    react-app :
        stdin_open: true
        build : 
            context : .
            dockerfile: Dockerfile.dev
        ports : 
            - "3000:3000"
        volumes : 
            - /usr/react-app/node_modules
            - .:/usr/react-app
    tests : 
        stdin_open : true
        build: 
            context : .
            dockerfile: Dockerfile.dev
        volumes: 
            - /usr/react-app/node_modules
            - .:/usr/react-app
        command: ["npm","run","test"]